//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.09 at 03:28:00 PM CEST 
//


package com.mile.soap.client.app.quiz;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mile.soap.client.app.quiz package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mile.soap.client.app.quiz
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Answer }
     * 
     */
    public Answer createAnswer() {
        return new Answer();
    }

    /**
     * Create an instance of {@link Question }
     * 
     */
    public Question createQuestion() {
        return new Question();
    }

    /**
     * Create an instance of {@link Category }
     * 
     */
    public Category createCategory() {
        return new Category();
    }

    /**
     * Create an instance of {@link DeleteAnswerRequest }
     * 
     */
    public DeleteAnswerRequest createDeleteAnswerRequest() {
        return new DeleteAnswerRequest();
    }

    /**
     * Create an instance of {@link AnswersForQuestionRequest }
     * 
     */
    public AnswersForQuestionRequest createAnswersForQuestionRequest() {
        return new AnswersForQuestionRequest();
    }

    /**
     * Create an instance of {@link UploadQuestionRequest }
     * 
     */
    public UploadQuestionRequest createUploadQuestionRequest() {
        return new UploadQuestionRequest();
    }

    /**
     * Create an instance of {@link GetCategoriesRequest }
     * 
     */
    public GetCategoriesRequest createGetCategoriesRequest() {
        return new GetCategoriesRequest();
    }

    /**
     * Create an instance of {@link AnswersResponse }
     * 
     */
    public AnswersResponse createAnswersResponse() {
        return new AnswersResponse();
    }

    /**
     * Create an instance of {@link AffectedRowsResponse }
     * 
     */
    public AffectedRowsResponse createAffectedRowsResponse() {
        return new AffectedRowsResponse();
    }

    /**
     * Create an instance of {@link CategoriesResponse }
     * 
     */
    public CategoriesResponse createCategoriesResponse() {
        return new CategoriesResponse();
    }

    /**
     * Create an instance of {@link QuestionResponse }
     * 
     */
    public QuestionResponse createQuestionResponse() {
        return new QuestionResponse();
    }

}
