//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.01 at 02:40:56 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.mile.com/collection/management/soap/Quiz", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.mile.soap.client.app.quiz;
